### ISSUE TITLE
Improvement : Fix card size,  Improve UI and update the card 

### ISSUE THREAD

**Issue by aialok** [aialok/open-source-IIIT-Ranchi#11]
Update the card template documentation in README.md
Improve UI, fix card overflow in sophomore section

**Comment by praptisharma28** [comment]
Hey @aialok ,I want to work on this, could you please assign it to me? Thank you!

**Comment by aialok** [comment]
Well this repo is for my college student only but you can fix this issue.

Card in the sophomore page are overflowing and there width are not of same size.
If you can fix it...then good to go.
