### ISSUE TITLE
ADD Some images and change the background colour

### ISSUE THREAD

**Issue by Yukrant** [aialok/open-source-IIIT-Ranchi#28]
I want to add some animation , make it responsive for small screen , change colour and background image.
Please assign it to me under Hacktoberfest 2023

**Comment by aialok** [comment]
I have assigned you the issue..you can improve the UI/UX of home screen , card and dropdown menu for the mobile view but dont change the color of homepage and the navigation bar in homepage

**Comment by aialok** [comment]
Hey @Yukrant  you are working in this issue.  Please update as soon as possible.

**Comment by suhas3145** [comment]
Hey , if possible could you assign the issue to me !!!!!

**Comment by aialok** [comment]
You just made a pull request I will accept it....you don't need to be assigned

**Comment by suhas3145** [comment]
Hey , could you clarify about what changes to be done ?

**Comment by aialok** [comment]
Well, you don't need to change anything you can make your card as pull request.
