### ISSUE TITLE
front page

### ISSUE THREAD

**Issue by Shrutibansal22** [aialok/open-source-IIIT-Ranchi#58]
I want to add css to the front page to make website look more attractive.
Kindly assign me this issue.

**Comment by aialok** [comment]
sure...go ahead and please change according to you. 

Also can you please remove IIIT Ranchi things make it general for all the college student.

Write some good description and title on page like learn to participate in hacktober fest things...

Thanks @Shrutibansal22  : )

**Comment by Shrutibansal22** [comment]
yes Sure.
Thanks for assigning me this task.

**Comment by Shrutibansal22** [comment]
Sir kindly assign me this task under hacktober fest.

**Comment by aialok** [comment]
Go ahead : )
Added label : )
